### ISSUE TITLE
Importing @connect from react-redux causes lodash-es to throw error.

### ISSUE THREAD

**Issue by birdiesanders** [reactql/examples#3] opened 2017-06-17 17:58 UTC
It seems to be the only thing that triggers this behaviour, but simply requiring react-redux can throw this into a panic. 

`import { connect } from 'react-redux'`

results in:

```
/home/birdie/react/yoreactrelaygql/examples/graphql-server/node_modules/lodash-es/isPlainObject.js:1
(function (exports, require, module, __filename, __dirname) { import baseGetTag from './_baseGetTag.js';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/birdie/react/yoreactrelaygql/examples/graphql-server/dist/server_dev.js:2686:18)
```

**Comment by leebenson** [comment] 2017-06-17 18:54
ReactQL's default webpack config doesn't do any transpilation of external NPM packages inside of `node_modules` on the server, so if you're using packages that use ES6 concepts such as `import/export` without transpiling down to CommonJS, they won't work.

The fix in this case is probably to use lodash proper and not `lodash-es`.

**Comment by birdiesanders** [comment] 2017-06-17 20:03
Ok, sounds reasonable. How would I go about getting this to work? I'm using node 8.1.2, so async await is fully implemented in my environment. 

_Sent from my Motorola Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by leebenson** [comment] 2017-06-17 20:17
Have you tried using `lodash` instead of `lodash-es`? The latter is what's throwing the error. That package specifically exports the non-transpiled, ES6 syntax; whereas `lodash` works everywhere.

The reasons not to transpile node_modules are:

1. Since `node_modules` is already installed on the server, there's no need to endure the cost/time of re-transpiling everything that's already installed. As a result, the resulting `server.js` is ~25kb instead of several megabytes.

2. Some modules have binary components, that don't transpile well to JS -- which is what the server environment is more likely to use (obviously, this isn't a factor in the browser-- there's no way that C/C++ mods, like some of the Webpack steps use, would ever work in the browser.)

3. All NPM packages should be Node-friendly, meaning they should output CommonJS modules and have their own transpilation step. `import/export` doesn't work in Node... it needs something like Babel to transpile it down to `require()` statements instead. Third-party NPM modules should take care of this for you, without requiring you to compile everything manually (which also takes ages).

4. Some third-party mods just don't play nicely with Webpack when building a Node compatible bundle. There's a ton of edge cases that would need configuring just to get the base installed, and it's very likely you'd find more in your own code.

**Comment by leebenson** [comment] 2017-06-17 20:18
To be clear, I should also add that the browser **_does_** transpile `node_modules` (to `vendor.js`, to be exact) -- the edge cases mentioned above don't typically apply to building a browser bundle, so we can get away with it. Plus we need to bundle everything anyway, since we're serving it all to the client.

**Comment by leebenson** [comment] 2017-06-17 20:23
Actually, addendum -

I see that it's `react-redux` that bundles `lodash-es`, not your own code.

Someone reported the same issue here:
https://github.com/reactjs/react-redux/issues/713

Could be because the react-redux build step isn't running properly that transpiles it, but I'm not able to replicate that locally -- I have `react-redux` running just fine in https://github.com/reactql/kit

Did you add `react-redux` yourself, or simply use the kit?

**Comment by wood1986** [comment] 2017-06-18 00:26
I personally think it is Redux-React issue but they 120% confirmed that it was not Redux-React issue. Ideally, they should only use non-es lodash regardless of whether it is a es6 app or not.  Now it becomes a problem

**Comment by birdiesanders** [comment] 2017-06-18 01:36
I added it via npm and went with it that way.  So I assume this is going to require a nice hack, or waiting until react-redux learns to play nice?

_Sent from my Motorola Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by leebenson** [comment] 2017-06-18 10:30
@birdiesanders - I actually have `react-redux` working well in [the main kit](https://github.com/reactql/kit). You can `npm run build-run` and it plays nicely on the server.

I'm not sure what's causing the edge case with reactjs/react-redux#713 without digging deeper. I initially suspected it was because `lodash-es` wasn't being transpiled properly, but it seems that react-redux is already compatible with usage via Node by virtue of their own internal build process and the fact they also bundle `lodash` proper.

My advice would be to start a new project with the [ReactQL CLI](https://github.com/reactql/cli) and then use the graphql-server code as inspiration to add a GraphQL server, if that's what you want to do. It should hopefully avoid this error.

Another thing I'd do, and I'm not at all sure whether this is related, is stick to NPM v5 and avoid using yarn for the time-being. Yarn doesn't run `postinstall` or certain build steps that NPM does, which - in certain edge cases - can prevent a third-party package for handling transpilation. That might not be the case here, but since sticking with NPM, I haven't encountered that same error again.

I'll close this for now, since `import { connect } from 'react-redux'` is working well in the main kit, in all environments.

**Closed as completed by leebenson** 2017-06-18 10:30 UTC

**Comment by birdiesanders** [comment] 2017-06-19 15:04
Using an OG require() makes it work. :/

**Comment by leebenson** [comment] 2017-06-19 17:48
Start with the main kit, and expand from there. It already includes react-redux, so when you start a new project, it should work out the box.

I'm not sure what's happening with your local config -- I'm able to `npm i -S react-redux` and then use `import { connect } from 'react-redux'` within `src/app.js` without issues. I don't need to drop down to a `require()`-- it works with 'import'.

Could be an installation issue? I'm using Node 8.1.2, NPM 5.0.3 running on macOS Sierra.

**Comment by birdiesanders** [comment] 2017-06-19 19:30
I'm a long ways off from being able to implement the graphql server into the kit on my own, but I'll try my damnedest.

**Comment by leebenson** [comment] 2017-06-19 19:41
I'd be interested to know exactly what steps you took to clone the repo, install the NPM packages and then install `react-redux` -- would you mind sharing @birdiesanders ?

I can't replicate the issue locally so I'm not sure if it's platform related, or whether it's a specific build step that is failing somewhere.

**Comment by birdiesanders** [comment] 2017-06-19 20:33
Well, I went with your intuition, and found a fun fringe case where nvm can be disabled, but still redirect npm to use a different node target binary from the rest of the environment. I removed NVM entirely, and blasted my environment to a clean sparkle, and it seems to work properly now, including using es6 includes.

**Comment by leebenson** [comment] 2017-06-20 08:41
Good to hear. @wood1986, does this help your use case? With a proper Webpack config, it looks like this shouldn't be an issue.

**Comment by jsplink** [comment] 2017-07-09 23:48
Well, this was still causing headaches in my case for whatever reason. It was only causing errors w/ `npm run server-dev`.

Here's the hack, non-cross-env fix I'm using in case anyone runs into this:
Under `package.json`:
```
{
    ...
    "scripts": {
       ...
       "postinstall": "rm -r $PWD/node_modules/lodash-es && ln -s $PWD/node_modules/lodash  $PWD/node_modules/lodash-es"
       ...
    },
    ...
}
```

**Comment by leebenson** [comment] 2017-07-10 06:22
Thanks for the tip, @jlsphar. I'm still not sure why lodash-es _occasionally_ throws errors, but doesn't in the majority of cases. Nice solution, though.

**Comment by wzup** [comment] 2017-12-13 10:49
FWIW
I had the same error thrown. In my case it was Webpack config entry that ignored to compile `lodash`. I just got rig `lodash` from regex and the error disappeared:

```
    module: {
        noParse: function(content) {
            return /jquery|lodash/.test(content); // <= Just delete that lodash from here
        },
```
